version: "3.4"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=NZ
    volumes:
      - sabnzbdconfig:/config
      - downloads:/downloads # download folder
    ports:
      - 8079:8079
    networks:
     - reverse_proxy
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=NZ # timezone, defined in .env
    volumes:
      - sonarrconfig:/config # config files
      - tv:/TV # tv shows folder
      - downloads:/downloads # download folder
    ports:
      - 8989:8989
    networks:
     - reverse_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.willg.link`)"
      - "traefik.http.routers.sonarr.middlewares=middlewares-authentik@docker"
      - "traefik.http.routers.sonarr.service=sonarr-media"
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=NZ # timezone, defined in .env
    volumes:
      - radarrconfig:/config # config files
      - movies:/Movies # movies folder
      - downloads:/downloads # download folder
    ports:
      - 7878:7878
    networks:
     - reverse_proxy


  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=NZ # timezone, defined in .env
    volumes:
      - plexconfig:/config # plex database
      - plexconfig:/transcode # temp transcoded files
      - tv:/tv # media library
      - movies:/movies # media library
    ports:
      -  32400:32400 
      -  5353:5353/udp 
      -  8324:8324 
      -  32410:32410/udp 
      -  32412:32412/udp 
      -  32413:32413/udp 
      -  32414:32414/udp 
      -  32469:32469
    networks:
     - reverse_proxy



volumes:
  downloads:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/media/Downloads'

  tv:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/media/TV'

  movies:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/media/Movies'
  
  plexconfig:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/container_data/media/plex'

  sonarrconfig:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/container_data/media/sonarr'

  radarrconfig:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/container_data/media/radarr'

  sabnzbdconfig:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/container_data/media/sabnzbd'

networks:
  reverse_proxy:
    external: true 