version: "3.8"

services:

  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    command:
      - --entrypoints.web.address=:80
      - --api
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAINNAME}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAINNAME}
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false 
      - --certificatesresolvers.letsencryptresolver.acme.dnschallenge=true
      - --certificatesresolvers.letsencryptresolver.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencryptresolver.acme.email=${EMAIL}
      - --certificatesresolvers.letsencryptresolver.acme.storage=/acme.json
      - --log.level=info
      - --providers.file.filename=/dynamic.yml
    ports:
      - 80:80
      - 443:443
  

    networks:
     - reverse_proxy

    environment:
      - CF_API_EMAIL=${EMAIL}
      - CF_API_KEY=${KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro # allow Traefik to listen to Docker events
      - ${TRAEFIK_DIR}/acme.json:/acme.json # stores ACME (HTTPS) certificates
      - /container_data/traefik/dynamic.yml:/dynamic.yml:ro

    labels:
      - traefik.enable=true

      # "admin" middleware definition
      # to be used by services that do not have their own security
      - traefik.http.middlewares.admin.basicauth.users=${HTTP_BASIC_USER}:${HTTP_BASIC_PWD}

      # expose the traefik dashboard
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.rule=Host(`${DOMAINNAME}`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=admin
      - traefik.http.routers.traefik.tls.certresolver=letsencryptresolver

      - traefik.http.middlewares.middlewares-authentik.forwardAuth.address=http://172.26.0.9:9000/outpost.goauthentik.io/auth/traefik
      - traefik.http.middlewares.middlewares-authentik.forwardAuth.trustForwardHeader=true
      - traefik.http.middlewares.middlewares-authentik.forwardAuth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
      
networks:
  reverse_proxy:
    external: true 