services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    networks:
      - reverse_proxy    
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.willg.link`)"


volumes:
  portainer_data:
    external: true
networks:
  reverse_proxy:
    external: true 