version: "3.8"
services:
  dashy:
    image: lissy93/dashy
    container_name: dashy
    volumes:
      - /home/will/dashy/dashy-conf.yml:/app/user-data/conf.yml
    ports:
      - 8090:8080
    networks:
      - reverse_proxy    
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashy.tls=true"
      - "traefik.http.routers.dashy.entrypoints=websecure"
      - "traefik.http.routers.dashy.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.dashy.rule=Host(`home.willg.link`)"
      - "traefik.http.routers.dashy.middlewares=middlewares-authentik@docker"
###############################################################
# Networks
###############################################################
networks:
  reverse_proxy:
    external: true