name: Update Docker Containers

on:
  push:
    branches:
      - main  

jobs:
  update:
    runs-on: self-hosted
    steps:
      - name: Change to project directory
        run: |
          cd /container_data/Docker || exit 1
          echo "Successfully changed to project directory"
        
      - name: Pull latest changes
        run: git pull 
        
      - name: Stop running containers
        run: docker-compose down
        
      - name: Start updated containers
        run: docker-compose up -d --build
