name: Update Docker Containers

on:
  push:
    branches:
      - main  # or whatever your default branch is named

jobs:
  update:
    runs-on: self-hosted
    steps:
      - name: Check current directory and change to project directory
        run: |
          echo "Current directory before change:"
          pwd
          ls -la
          echo "Changing to /container_data/Docker"
          cd /container_data/Docker || exit 1
          echo "Current directory after change:"
          pwd
          ls -la

      - name: Configure Git
        working-directory: /container_data/Docker
        run: |
          git config --global --add safe.directory /container_data/Docker
          git config --global user.email "runner@github.com"
          git config --global user.name "GitHub Runner"

      - name: Pull latest changes
        working-directory: /container_data/Docker
        run: |
          git fetch origin
          git reset --hard origin/main

      - name: Stop running containers
        working-directory: /container_data/Docker
        run: docker-compose down

      - name: Start updated containers
        working-directory: /container_data/Docker
        run: docker-compose up -d --build
