name: Check Runner User and Permissions

on:
  push:
    branches:
      - main

jobs:
  check-user:
    runs-on: self-hosted
    steps:
      - name: Check current user and environment
        run: |
          echo "Current user:"
          id
          echo "User's groups:"
          groups
          echo "Process information:"
          ps aux | grep actions-runner
          echo "Runner directory permissions:"
          ls -la /home/will/actions-runner
          echo "Docker directory permissions:"
          ls -la /container_data/Docker

      - name: Check Docker permissions
        run: |
          docker info || echo "Docker not accessible"
          docker-compose version || echo "docker-compose not accessible"