name: Update Docker Containers

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: self-hosted
    steps:
      - name: Change to project directory and pull changes
        run: |
          cd /container_data/Docker
          git pull origin main

      - name: Stop running containers
        run: docker-compose down

      - name: Start updated containers
        run: docker-compose up -d --build

      - name: Check Docker status
        run: |
          docker info
          docker-compose version
