name: Update Docker Containers

on:
  push:
    branches:
      - main  # or whatever your default branch is named

jobs:
  update:
    runs-on: self-hosted
    steps:
      - name: Change to project directory and check contents
        run: |
          cd /container_data/Docker || exit 1
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la

      - name: Configure Git
        working-directory: /container_data/Docker
        run: |
          git config --global --add safe.directory /container_data/Docker
          git config --global user.email "runner@github.com"
          git config --global user.name "GitHub Runner"
          echo "Updated Git config:"
          git config --list

      - name: Pull latest changes
        working-directory: /container_data/Docker
        run: |
          git fetch origin
          git reset --hard origin/main

      - name: Stop running containers
        working-directory: /container_data/Docker
        run: docker-compose down

      - name: Start updated containers
        working-directory: /container_data/Docker
        run: docker-compose up -d --build
