name: YAML Lint

on: [push, pull_request]

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/
          config_data: |
            extends: default
            rules:
              line-length:
                max: 120
                level: warning
              truthy:
                check-keys: false